- name: Stop VM server
  ignore_errors: true
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ hostvars[item].ansible_vmid }}"
    node: "{{ proxmox_node }}"
    state: absent
  loop: "{{ groups['k3s-master'] }}"

- name: Stop VM worker
  ignore_errors: true
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ hostvars[item].ansible_vmid }}"
    node: "{{ proxmox_node }}"
    state: absent
  loop: "{{ groups['k3s-worker'] }}"